<div class="book_article_texttitle">  
 
     {dede:type}<a href='[field:typelink/]'>[field:typename/]</a>{/dede:type}      


 
 </div>     {dede:channel type='son' noself='yes'}    <div class="book_article_listtext"><dl id="chapterlist">    <dd>	   

 <a href='[field:typelink/]'>[field:typename/]</a>    	</dd>    <dd>	    
 
 </dl><div class="clear"></div></div>   {/dede:channel}    <div class="clear"></div></div>